name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch: [x64]
        os: [ubuntu-latest]
        python-version: ["3.10.x"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          architecture: ${{ matrix.arch }}
          python-version: ${{ matrix.python-version }}
      - name: Set up Poetry and upgrade pip
        run: |
          pip install -U pip poetry
      - name: Install test dependencies
        run: |
          pip install --prefer-binary -r requirements-test.txt
      - name: Install flows
        run: |
          pip install --prefer-binary .
      - name: Check if `prefect build` works
        run: |
          prefect build
      - name: Get changed files for code tree analysis
        id: files
        uses: Ana06/get-changed-files@v2.1.0
      - name: Perform code tree analysis
        id: code-tree-analysis
        continue-on-error: true
        run: |
          python .github/workflows/scripts/code_tree_analysis.py "${{ steps.files.outputs.all }}"
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: "${{ steps.code-tree-analysis.outputs.pr-message }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
